### ISSUE TITLE
When is the code open source

### ISSUE THREAD

**Issue by github-eliviate** [cherise215/MaxStyle#1]
dear cherise:
    I have readed your paper ,and I'm very interested in your work, shall i know when is the code open source?
    Best Regards
    eliviate

**Comment by cherise215** [comment]
Dear Eliviate,

Thanks for your interest. We plan to publish our code ASAP. However, as I am currently on an extreme busy schedule. It is likely to be ready around late July or early August. Since our code is based on MixStyle, you can first have a look at https://github.com/KaiyangZhou/mixstyle-release. The dual-branch network we used is provided in our previous work: https://github.com/cherise215/Cooperative_Training_and_Latent_Space_Data_Augmentation. (w/o the second shape refinement network)

**Comment by cherise215** [comment]
Hi Eliviate, the code has been released.

**Comment by github-eliviate** [comment]
copy that ,thank you
